name: Hello World

# トリガーの設定
on:
  workflow_dispatch: # 手動実行用
  push:
    branches: main

# 実行するjobの設定
jobs:
  build:
    runs-on: ubuntu-latest # 実行環境

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 実行ブランチ

      - name: Run echo command
        run: echo Hello, world! # Hello World!と出力する
